[build]
  publish = "dist"
  command = "yarn build"

[build.environment]
  NODE_VERSION = "18.19.0"  # LTS version with good compatibility
  NPM_FLAGS = "--no-optional"

# Use latest stable Ubuntu image
[build.image]
  ubuntu = "jammy"  # Ubuntu 22.04 LTS
